export const BANGLADESH_CITIES = [
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Barishal',
  'Bhola',
  'Bogura',
  'Brahmanbaria',
  'Chandpur',
  'Chapai Nawabganj',
  'Chattogram',
  'Chuadanga',
  'Cumilla',
  'Cox’s Bazar',
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jamalpur',
  'Jashore',
  'Jhalokathi',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachhari',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmipur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rajshahi',
  'Rangamati',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Sylhet',
  'Tangail',
  'Thakurgaon'
];
export const SPECIALTIES = [
  'Medicine',
  'Cardiology',
  'Orthopedics',
  'Gynecology',
  'Pediatrics',
  'Dermatology',
  'ENT',
  'Neurology',
  'Urology',
  'Dentistry',
  'Psychiatry',
  'Ophthalmology',
  'General Surgery',

  // Additional common specialties
  // 'General Medicine',
  // 'Orthopedic',
  // 'Child Specialist',
  // 'Skin Specialist',
  // 'Gynecology & Obstetrics',
  // 'Neurosurgery',
  // 'Cardiac Surgery',
  // 'Nephrology',
  // 'Gastroenterology',
  // 'Endocrinology',
  // 'Pulmonology',
  // 'Oncology',
  // 'Hematology',
  // 'Rheumatology',
  // 'Infectious Disease',
  // 'Plastic Surgery',
  // 'Vascular Surgery',
  // 'Anesthesiology',
  // 'Pathology',
  // 'Radiology',
  // 'Physical Medicine',
  // 'Family Medicine'
];